require_relative "boot"

# Ensure Active Record encryption keys and secret key base exist for encrypted attributes and sessions.
# In production and development, fall back to persisted key files if env vars are missing.
# This is needed because Thruster doesn't pass env vars to the Rails subprocess,
# and running commands via `docker exec` bypasses `docker-entrypoint`.
rails_env = ENV["RAILS_ENV"] || ENV["RACK_ENV"] || "development"
if rails_env != "test"
  # Load SECRET_KEY_BASE if missing
  if ENV["SECRET_KEY_BASE"].nil? && ENV["RAILS_MASTER_KEY"].nil?
    secret_file = File.expand_path("../storage/.secret_key_base", __dir__)
    if File.exist?(secret_file)
      ENV["SECRET_KEY_BASE"] = File.read(secret_file).strip
    end
  end

  # Load Active Record encryption keys
  required_keys = %w[
    ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
  ].freeze

  missing_keys = required_keys.reject { |key| ENV[key].present? }

  if missing_keys.any?
    key_file = File.expand_path("../storage/.encryption_keys", __dir__)

    if File.exist?(key_file)
      # Load keys from file (generated by docker-entrypoint)
      File.read(key_file).each_line do |line|
        if line =~ /^export\s+(\w+)="([^"]+)"$/
          ENV[$1] ||= $2
        end
      end
    else
      # Generate new keys and persist them (for development/first run)
      require "securerandom"
      require "fileutils"

      ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"] = SecureRandom.base64(32)
      ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"] = SecureRandom.base64(32)
      ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"] = SecureRandom.base64(32)

      FileUtils.mkdir_p(File.dirname(key_file))
      File.write(
        key_file,
        <<~KEYS
          export ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY="#{ENV["ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY"]}"
          export ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY="#{ENV["ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY"]}"
          export ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT="#{ENV["ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT"]}"
        KEYS
      )
      File.chmod(0o600, key_file)
    end
  end
end


require "rails"
# Pick the frameworks you want:
require "active_model/railtie"
require "active_job/railtie"
require "active_record/railtie"
require "active_storage/engine"
require "action_controller/railtie"
require "action_mailer/railtie"
# require "action_mailbox/engine"
# require "action_text/engine"
require "action_view/railtie"
require "action_cable/engine"
require "rails/test_unit/railtie"

# Require the gems listed in Gemfile, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(*Rails.groups)

module Shelfarr
  class Application < Rails::Application
    # Initialize configuration defaults for originally generated Rails version.
    config.load_defaults 8.1

    # Support running the app at a sub-path (e.g., /shelfarr)
    # Set RAILS_RELATIVE_URL_ROOT environment variable to configure
    config.relative_url_root = ENV.fetch("RAILS_RELATIVE_URL_ROOT", "/")

    # Covers and store links are supplied by external catalog providers. Avoid
    # disclosing a self-hosted Shelfarr URL while retaining the origin for
    # same-origin form submissions such as the OIDC handoff.
    config.action_dispatch.default_headers["Referrer-Policy"] = "same-origin"

    # Please, add to the `ignore` list any other `lib` subdirectories that do
    # not contain `.rb` files, or that should not be reloaded or eager loaded.
    # Common ones are `templates`, `generators`, or `middleware`, for example.
    config.autoload_lib(ignore: %w[assets tasks])

    # Configuration for the application, engines, and railties goes here.
    #
    # These settings can be overridden in specific environments using the files
    # in config/environments, which are processed later.
    #
    # config.time_zone = "Central Time (US & Canada)"
    # config.eager_load_paths << Rails.root.join("extras")
  end
end
